[project]
name = "spovis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.5"
dependencies = [
    "numpy>=1.24.4",
    "openpyxl>=3.1.5",
    "pandas>=2.0.3",
    "pillow>=10.4.0",
    "xlrd>=2.0.1",
]
